import { useState } from "react";
import { motion } from "motion/react";
import { 
  ArrowLeft, FileText, Download, Star, ExternalLink, 
  CheckCircle, Copy, HelpCircle, GraduationCap, ChevronRight, Share2 
} from "lucide-react";
import { Project } from "../types";

interface DetailedProjectViewProps {
  project: Project;
  onBack: () => void;
  onSave: (project: Project) => void;
  isSaved: boolean;
  userEmail?: string;
}

export default function DetailedProjectView({ project, onBack, onSave, isSaved, userEmail }: DetailedProjectViewProps) {
  const [copiedSection, setCopiedSection] = useState<string | null>(null);
  const [copiedLink, setCopiedLink] = useState(false);

  // Interactive feedback loop states for server-side dataset analysis
  const [selectedRating, setSelectedRating] = useState(0);
  const [hoveredRating, setHoveredRating] = useState(0);
  const [feedbackComment, setFeedbackComment] = useState("");
  const [isSubmittingFeedback, setIsSubmittingFeedback] = useState(false);
  const [hasSubmittedFeedback, setHasSubmittedFeedback] = useState(false);
  const [feedbackError, setFeedbackError] = useState("");

  const handleSubmitFeedback = async () => {
    if (selectedRating === 0) {
      setFeedbackError("Please select a star rating first.");
      return;
    }
    setIsSubmittingFeedback(true);
    setFeedbackError("");
    try {
      const res = await fetch("/api/feedback", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          projectId: project.id,
          projectTitle: project.title,
          rating: selectedRating,
          comment: feedbackComment,
          email: userEmail || "anonymous"
        })
      });

      if (!res.ok) {
        throw new Error("Failed to save rating on the server.");
      }
      setHasSubmittedFeedback(true);
    } catch (err: any) {
      console.warn("Feedback fail:", err);
      setFeedbackError(err.message || "Failed to submit feedback. Check server connection.");
    } finally {
      setIsSubmittingFeedback(false);
    }
  };

  const handleCopyText = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(label);
    setTimeout(() => setCopiedSection(null), 2000);
  };

  const handleShareLink = () => {
    const shareUrl = `${window.location.origin}?project=${encodeURIComponent(project.title)}`;
    navigator.clipboard.writeText(shareUrl);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2000);
  };

  // Generates Markdown Representation for download
  const handleExportMarkdown = () => {
    const mdContent = `
# Project Blueprint: ${project.title}
*Generated by GitHub Project Mentor AI*

## Summary
${project.summary}

## Difficulty & Impact Metrics
- **Difficulty Score:** ${project.difficultyScore}/10 (${project.difficulty})
- **GitHub Portfolio Value:** ${project.portfolioValue}/100
- **Research Potential:** ${project.researchPotential}/100
- **Innovation Index:** ${project.innovationScore}/100
- **GitHub Readiness Index:** ${project.githubReadinessScore}%

## Unexplored Research Gap
${project.researchGap}

## Problem Statement
${project.problemStatement}

## Target Users
${project.targetUsers.map(u => `- ${u}`).join("\n")}

## System Architecture Narrative
${project.systemArchitecture}

### Key Architectural Services
${project.archComponents.map(c => `- **${c.title}**: ${c.desc}`).join("\n")}

## Recommended Technology Stack
${project.recommendedTechStack.map(t => `- ${t}`).join("\n")}

## Dataset Suggestions
${project.datasetSuggestions.map(d => `- **${d.name}**: ${d.description} (Find or search via: ${d.urlPlaceholder})`).join("\n")}

## Academic Papers & Literature to Study
${project.researchPapers.map(p => `- **${p.title}** (${p.link}): ${p.significance}`).join("\n")}

## Complete Step-by-Step Development Roadmap
${project.developmentRoadmap.map(r => `### ${r.phase} (Weight/Duration: ${r.duration})\n${r.tasks.map(t => `  - [ ] ${t}`).join("\n")}`).join("\n\n")}

## Publication Opportunities
${project.publicationOpportunities.map(o => `- **Venue**: ${o.venue}\n  - *Thesis Direction*: ${o.researchDirection}`).join("\n")}

## Future Scale & Research Extensions
${project.futureExtensions.map(f => `- ${f}`).join("\n")}

## GSoC Relevance & Open Source Alignment
${project.gsocRelevance}

## Patent Potential & Algorithms
${project.patentPotential}

## Optimized Resume Bullet Points (Copy into CV!)
${project.resumeImpact.map(b => `- ${b}`).join("\n")}
`;

    const blob = new Blob([mdContent.trim()], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `${project.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-blueprint.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 py-6 font-sans text-slate-100">
      
      {/* Top action bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-8">
        <button
          onClick={onBack}
          id="btn-back-detail"
          className="flex items-center gap-1 text-[#8B949E] hover:text-white text-sm font-medium transition cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to recommendations
        </button>

        <div className="flex flex-wrap gap-2.5 w-full sm:w-auto">
          <button
            onClick={handleShareLink}
            id="btn-share-link"
            className="flex-1 sm:flex-initial px-4 py-2 bg-[#21262D] border border-[#30363D] hover:bg-[#30363D] rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition cursor-pointer"
          >
            <Share2 className="w-3.5 h-3.5" />
            {copiedLink ? "Link Copied!" : "Share Link"}
          </button>

          <button
            onClick={handleExportMarkdown}
            id="btn-export-markdown"
            className="flex-1 sm:flex-initial px-4 py-2 bg-[#21262D] border border-[#30363D] hover:bg-[#30363D] text-sky-400 border-sky-500/20 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition cursor-pointer"
          >
            <FileText className="w-3.5 h-3.5" />
            Export Blueprint (MD)
          </button>

          <button
            onClick={() => onSave(project)}
            id="btn-save-detail"
            className={`flex-1 sm:flex-initial px-4 py-2 hover:opacity-90 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition cursor-pointer ${
              isSaved 
                ? "bg-amber-500/10 text-amber-300 border border-amber-500/40" 
                : "bg-gradient-to-r from-sky-500 to-indigo-600 text-slate-950 font-bold"
            }`}
          >
            <Star className="w-3.5 h-3.5 fill-current" />
            {isSaved ? "Saved in Favorites" : "Save Blueprint"}
          </button>
        </div>
      </div>

      {/* Main Title Badge Matrix */}
      <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-6 sm:p-8 mb-8 shadow-md">
        <div className="flex flex-col md:flex-row justify-between items-start gap-4 mb-4">
          <div>
            <h1 className="text-2xl sm:text-3xl font-sans font-extrabold text-white tracking-tight">
              {project.title}
            </h1>
            <p className="text-[#8B949E] text-sm mt-2 max-w-4xl">
              {project.summary}
            </p>
          </div>
        </div>

        {/* Big Matrix Scores */}
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4 pt-6 border-t border-[#30363D] text-center mt-6">
          <div className="p-3 bg-[#0D1117] rounded-lg border border-[#30363D]">
            <span className="block text-[10px] text-[#8B949E] uppercase tracking-wide font-bold">Innovation Index</span>
            <span className="text-xl sm:text-2xl font-bold text-white">{project.innovationScore}<span className="text-xs text-[#8B949E]">/100</span></span>
          </div>

          <div className="p-3 bg-[#0D1117] rounded-lg border border-[#30363D]">
            <span className="block text-[10px] text-[#8B949E] uppercase tracking-wide font-bold">Difficulty Score</span>
            <span className="text-xl sm:text-2xl font-bold text-amber-400">{project.difficultyScore}<span className="text-xs text-[#8B949E]">/10</span></span>
          </div>

          <div className="p-3 bg-[#0D1117] rounded-lg border border-[#30363D]">
            <span className="block text-[10px] text-[#8B949E] uppercase tracking-wide font-bold">GitHub Portfolio</span>
            <span className="text-xl sm:text-2xl font-bold text-emerald-400">{project.portfolioValue}<span className="text-xs text-[#8B949E]">/100</span></span>
          </div>

          <div className="p-3 bg-[#0D1117] rounded-lg border border-[#30363D]">
            <span className="block text-[10px] text-[#8B949E] uppercase tracking-wide font-bold">Research Potential</span>
            <span className="text-xl sm:text-2xl font-bold text-indigo-400">{project.researchPotential}<span className="text-xs text-[#8B949E]">/100</span></span>
          </div>

          <div className="p-3 bg-[#0D1117] rounded-lg border border-[#30363D] col-span-2 md:col-span-1">
            <span className="block text-[10px] text-[#8B949E] uppercase tracking-wide font-bold">Recruiter Readiness</span>
            <span className="text-xl sm:text-2xl font-bold text-sky-400">{project.githubReadinessScore}%</span>
          </div>
        </div>
      </div>

      {/* Main Grid content */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left main area (col-span-2) */}
        <div className="lg:col-span-2 space-y-8">
          
          {/* Problem Statement & User Gap */}
          <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-6">
            <div className="border-b border-[#30363D] pb-3 mb-4 flex items-center justify-between">
              <h3 className="text-base font-bold text-white uppercase tracking-wider font-mono">
                Academic Research Gap & Problem
              </h3>
              <button 
                onClick={() => handleCopyText(project.problemStatement, "prob")}
                className="text-xs text-slate-500 hover:text-[#C9D1D9] flex items-center gap-1 cursor-pointer"
              >
                <Copy className="w-3.5 h-3.5" />
                {copiedSection === "prob" ? "Copied" : "Copy"}
              </button>
            </div>
            
            <p className="text-sm font-semibold text-emerald-400/95 leading-relaxed bg-emerald-950/20 p-3.5 border border-emerald-500/20 rounded-lg mb-4">
              <span className="font-bold block text-xs uppercase tracking-wide text-emerald-300 font-mono mb-1">Identified Research Gap:</span>
              {project.researchGap}
            </p>

            <h4 className="text-xs font-bold uppercase text-[#8B949E] tracking-wider mb-2 font-mono">Target Problem Statement</h4>
            <p className="text-sm text-[#C9D1D9] leading-relaxed">
              {project.problemStatement}
            </p>

            <div className="mt-5">
              <h4 className="text-xs font-bold uppercase text-[#8B949E] tracking-wider mb-2 font-mono">Target Benefiting Demographics</h4>
              <div className="flex flex-wrap gap-2">
                {project.targetUsers.map((user, idx) => (
                  <span key={idx} className="px-3 py-1 bg-[#0D1117] border border-[#30363D] text-xs rounded-full">
                    🧑‍💻 {user}
                  </span>
                ))}
              </div>
            </div>
          </div>

          {/* System Architecture & Component Mapping */}
          <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-6">
            <div className="border-b border-[#30363D] pb-3 mb-4 flex items-center justify-between">
              <h3 className="text-base font-bold text-white uppercase tracking-wider font-mono">
                System Architecture Blueprint
              </h3>
            </div>
            <p className="text-sm text-[#C9D1D9] leading-relaxed mb-6">
              {project.systemArchitecture}
            </p>

            {/* Interactive flow boxes */}
            <h4 className="text-xs font-bold uppercase text-[#8B949E] tracking-wider mb-3 font-mono">Architectural Components</h4>
            <div className="space-y-3">
              {project.archComponents.map((component, idx) => (
                <div key={idx} className="p-4 bg-[#0D1117] border border-[#30363D] rounded-lg hover:border-slate-700 transition">
                  <div className="flex items-center gap-2 mb-1.5">
                    <span className="w-5 h-5 rounded bg-indigo-500/10 text-indigo-400 text-xs font-mono font-bold flex items-center justify-center">
                      {idx + 1}
                    </span>
                    <span className="font-bold text-sm text-white">{component.title}</span>
                  </div>
                  <p className="text-xs text-[#8B949E] leading-relaxed pl-7">
                    {component.desc}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Development Roadmap */}
          <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-6">
            <div className="border-b border-[#30363D] pb-3 mb-5">
              <h3 className="text-base font-bold text-white uppercase tracking-wider font-mono">
                Interactive Sprint Roadmap
              </h3>
            </div>

            <div className="relative border-l border-[#30363D] pl-6 ml-3 space-y-8">
              {project.developmentRoadmap.map((phase, pIdx) => (
                <div key={pIdx} className="relative">
                  {/* Circle locator on left */}
                  <span className="absolute -left-9 top-1 w-6 h-6 rounded-full bg-[#161B22] border border-[#30363D] text-xs font-bold text-sky-400 flex items-center justify-center shadow-sm">
                    {pIdx + 1}
                  </span>

                  <div className="flex items-baseline justify-between gap-2 flex-wrap pb-1.5">
                    <h4 className="font-bold text-sm text-white">{phase.phase}</h4>
                    <span className="text-xs font-mono font-semibold text-[#8B949E] px-2 py-0.5 bg-[#0D1117] rounded border border-[#30363D]">
                      ⏱️ {phase.duration}
                    </span>
                  </div>

                  <ul className="space-y-2 mt-3 pl-3">
                    {phase.tasks.map((task, tIdx) => (
                      <li key={tIdx} className="text-xs text-[#C9D1D9] flex items-start gap-2.5 bg-[#0D1117]/30 p-2 border border-[#30363D]/40 rounded hover:border-[#30363D]">
                        <CheckCircle className="w-3.5 h-3.5 text-sky-400 mt-0.5 shrink-0" />
                        <span>{task}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>

          {/* Student Resume / Curated CV Impact Bullet Points */}
          <div className="bg-gradient-to-r from-sky-500/5 to-indigo-600/5 border border-sky-500/20 rounded-xl p-6">
            <div className="pb-3 border-b border-[#30363D]/60 mb-4 flex items-center justify-between">
              <h3 className="text-base font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2">
                🏆 Resume / CV Impact Boosters
              </h3>
              <button 
                onClick={() => handleCopyText(project.resumeImpact.join("\n"), "resume")}
                className="text-xs text-sky-400 hover:text-sky-300 flex items-center gap-1 cursor-pointer"
              >
                <Copy className="w-3.5 h-3.5" />
                {copiedSection === "resume" ? "Bullet Points Copied!" : "Copy Bullets"}
              </button>
            </div>
            
            <p className="text-xs text-[#8B949E] mb-4 leading-relaxed font-sans">
              Copy and Paste these high-impact, actionable action-results statements directly into your target resumes and portfolios once complete:
            </p>

            <div className="space-y-2.5">
              {project.resumeImpact.map((bullet, idx) => (
                <div key={idx} className="p-3 bg-slate-950/40 border border-slate-900 rounded-lg text-xs leading-relaxed text-[#C9D1D9]">
                  📌 {bullet}
                </div>
              ))}
            </div>
          </div>

          {/* AI Model Optimization / Rating & Feedback Mechanism */}
          <div className="bg-[#161B22] border border-[#30363D] hover:border-[#1F6FEB]/30 rounded-xl p-5 sm:p-6 transition shadow-sm">
            <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2 mb-2">
              🧠 AI Model Fine-Tuning Feedback
            </h3>
            <p className="text-xs text-[#8B949E] mb-5 leading-relaxed">
              Did this tailored blueprint provide high portfolio and pedagogical value? Leave a quick rating is a secure way to help us improve future recommendations.
            </p>

            {hasSubmittedFeedback ? (
              <motion.div 
                initial={{ opacity: 0, y: 5 }}
                animate={{ opacity: 1, y: 0 }}
                className="p-4 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded-lg flex items-center gap-3"
              >
                <CheckCircle className="w-5 h-5 text-emerald-400 shrink-0" />
                <div className="text-xs">
                  <p className="font-bold">Rating Submitted Successfully!</p>
                  <p className="text-[#8B949E] mt-0.5">Your evaluation was saved locally and is instantly available for model fine-tuning analysis.</p>
                </div>
              </motion.div>
            ) : (
              <div className="space-y-4">
                {/* Score Selector Inputs */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 bg-[#0D1117] border border-[#30363D] rounded-lg">
                  <div>
                    <span className="block text-xs font-bold text-white uppercase tracking-wide font-mono">Concept Quality:</span>
                    <span className="text-[10px] text-[#8B949E]">1 (Poor) to 5 (Outstanding)</span>
                  </div>

                  {/* Stars interactive */}
                  <div className="flex items-center gap-1">
                    {[1, 2, 3, 4, 5].map((val) => (
                      <button
                        key={val}
                        type="button"
                        onClick={() => setSelectedRating(val)}
                        onMouseEnter={() => setHoveredRating(val)}
                        onMouseLeave={() => setHoveredRating(0)}
                        id={`feedback-star-${val}`}
                        className="p-1 focus:outline-none cursor-pointer group transition-transform hover:scale-110"
                      >
                        <Star 
                          className={`w-6 h-6 transition-colors ${
                            val <= (hoveredRating || selectedRating)
                              ? "text-amber-400 fill-amber-400"
                              : "text-slate-600 hover:text-amber-400"
                          }`} 
                        />
                      </button>
                    ))}
                  </div>
                </div>

                {/* Optional comment text field */}
                <div>
                  <label htmlFor="feedback-comment" className="block text-xs font-bold text-[#8B949E] uppercase tracking-wider mb-2 font-mono">
                    Qualitative Recommendation Notes (Optional):
                  </label>
                  <textarea
                    id="feedback-comment"
                    value={feedbackComment}
                    onChange={(e) => setFeedbackComment(e.target.value)}
                    placeholder="E.g., Add more PyTorch details, suggest alternative open datasets, or detail why you picked this rating..."
                    className="w-full h-18 px-3.5 py-2.5 bg-[#0D1117] border border-[#30363D] focus:border-sky-500 rounded-lg text-xs text-[#C9D1D9] focus:outline-none transition resize-none placeholder:text-slate-600"
                  />
                </div>

                {/* Submit button */}
                <div className="flex justify-between items-center pt-2">
                  <div className="text-[10px] text-[#8B949E]">
                    {feedbackError && (
                      <span className="text-rose-400 font-semibold">{feedbackError}</span>
                    )}
                  </div>
                  <button
                    type="button"
                    onClick={handleSubmitFeedback}
                    disabled={isSubmittingFeedback || selectedRating === 0}
                    id="btn-submit-feedback"
                    className="px-4 py-2 bg-[#21262D] border border-[#30363D] hover:bg-sky-500/10 hover:border-sky-500/30 hover:text-sky-400 disabled:opacity-40 disabled:hover:bg-[#21262D] disabled:hover:border-[#30363D] disabled:hover:text-[#8B949E] text-xs font-bold text-slate-300 rounded-lg transition cursor-pointer flex items-center gap-1.5"
                  >
                    {isSubmittingFeedback ? "Saving Feedback..." : "Submit Quality Rating"}
                  </button>
                </div>
              </div>
            )}
          </div>

        </div>

        {/* Right sidebars/meta column (col-span-1) */}
        <div className="space-y-6">
          
          {/* Detailed recommended tools */}
          <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-5">
            <h4 className="text-xs font-bold text-[#8B949E] uppercase tracking-wider mb-3 block font-mono">
              Expert Tech Stack Selection
            </h4>
            <div className="flex flex-wrap gap-2">
              {project.recommendedTechStack.map((tech, idx) => (
                <span key={idx} className="px-3 py-1 bg-[#0D1117] border border-[#30363D] text-xs font-mono rounded text-sky-300">
                  {tech}
                </span>
              ))}
            </div>
          </div>

          {/* GSoC & Open Source validation */}
          <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-5">
            <h4 className="text-xs font-bold text-[#8B949E] uppercase tracking-wider mb-2 block font-mono">
              GSoC & CNCF Relevance
            </h4>
            <p className="text-xs text-[#C9D1D9] leading-relaxed">
              {project.gsocRelevance}
            </p>
          </div>

          {/* Dataset Suggestions */}
          <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-5">
            <h4 className="text-xs font-bold text-[#8B949E] uppercase tracking-wider mb-3 block font-mono">
              Suggested Open Data Sets
            </h4>
            <div className="space-y-3">
              {project.datasetSuggestions.map((dataset, idx) => (
                <div key={idx} className="bg-[#0D1117] border border-[#30363D] p-3 rounded-lg text-xs">
                  <span className="font-bold text-[#C9D1D9] block">{dataset.name}</span>
                  <p className="text-[#8B949E] mt-1 mb-2 leading-relaxed">
                    {dataset.description}
                  </p>
                  <span className="text-[10px] text-sky-400 font-mono block">
                    Source: {dataset.urlPlaceholder}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Academic Papers to Study */}
          <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-5">
            <h4 className="text-xs font-bold text-[#8B949E] uppercase tracking-wider mb-3 block font-mono">
              Pivotal Research Literature
            </h4>
            <div className="space-y-3.5">
              {project.researchPapers.map((paper, idx) => (
                <div key={idx} className="bg-[#0D1117] border border-[#30363D] p-3 rounded-lg text-xs">
                  <div className="flex items-center gap-1.5 text-slate-200">
                    <GraduationCap className="w-3.5 h-3.5 text-sky-400" />
                    <span className="font-bold line-clamp-1">{paper.title}</span>
                  </div>
                  <p className="text-[10px] text-[#8B949E] mt-1 font-mono italic">
                    Citation index: {paper.link}
                  </p>
                  <p className="text-[#8B949E] mt-2 leading-relaxed">
                    {paper.significance}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Peer-review Publishing Opportunities */}
          <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-5">
            <h4 className="text-xs font-bold text-[#8B949E] uppercase tracking-wider mb-3 block font-mono">
              Draft Target Venues
            </h4>
            <div className="space-y-3 text-xs text-[#C9D1D9]">
              {project.publicationOpportunities.map((o, idx) => (
                <div key={idx} className="border-l-2 border-indigo-500 pl-3">
                  <strong className="block text-white text-xs">{o.venue}</strong>
                  <p className="text-[#8B949E] text-[11px] mt-1 leading-relaxed">
                    {o.researchDirection}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Future Scaling scope */}
          <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-5">
            <h4 className="text-xs font-bold text-[#8B949E] uppercase tracking-wider mb-2 block font-mono">
              Future V2 Scale-Ups
            </h4>
            <ul className="space-y-1.5 pl-4 list-disc text-xs text-[#8B949E] leading-relaxed">
              {project.futureExtensions.map((f, idx) => (
                <li key={idx}>{f}</li>
              ))}
            </ul>
          </div>

          {/* Intellectual Property Patent options */}
          <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-5">
            <h4 className="text-xs font-bold text-[#8B949E] uppercase tracking-wider mb-2 block font-mono">
              Patent Potential / Utility draft
            </h4>
            <p className="text-xs text-[#8B949E] leading-relaxed">
              {project.patentPotential}
            </p>
          </div>

        </div>

      </div>
    </div>
  );
}
